version: 2
jobs:
  build:
    docker:
      - image: clojure:tools-deps

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: v1-dependencies-{{ checksum "deps.edn" }}

      - run: clojure -A:test -Stree

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: v1-dependencies-{{ checksum "deps.edn" }}

      - run:
          name: test CLJ
          command: clojure -A:test

      # - run:
      #     name: test CLJS
      #     command: lein test-cljs-none once

      # - run:
      #     name: test CLJS min
      #     command: lein test-cljs-min once
